### ISSUE TITLE
Issue during "Collecting receiver stats" when increasing --num-frames

### ISSUE THREAD

**Issue by JorgeSasiain** [NXP/isochron#23]
Hi,

I have a weird problem that when I increase --num-frames above a certain number (around 40-50 frames but it doesn't seem consistent), isochron seems to freeze after printing "Collecting receiver stats" without the .dat file being written.

This is my script:

```
#!/bin/bash

iface="eno2"
vlan="101"
stats_port="5101"
prio="1"

isochron send --interface "$iface" --vid "$vlan" --priority $prio --stats-port "$stats_port" --base-time 0 --advance-time 1 --shift-time 0 --cycle-time 0.01 --window-size 2500000 --num-frames 20 --frame-size 64 --client 10.0.101.133 --taprio --l2 --transport-specific 1 --omit-sync  --etype "0x$(printf '%x' $stats_port)" --output-file isochron.dat

isochron report  --input-file isochron.dat       --printf-format "seqid %u scheduled for %T, wake up %T, TX qdisc %T sw %T hw %T, RX hw %T sw %T\n"  --printf-args "qSwstTRr"   --start 1 --stop 20
```

This is the result with --num-frames 20

```
Using the kernel UTC-TAI offset which is 0
Destination MAC address is 3c:ec:ef:79:27:e9
Link state of node remote is running
Link state of node local is running
         Now:   1728907850.299592711
First wakeup:   1728907850.799999999
   Base time:   1728907850.800000000
  Cycle time:            0.010000000
Collecting receiver stats
seqid 1 scheduled for 1728907850.800000000, wake up 1728907850.800138489, TX qdisc 1728907850.800154509 sw 1728907850.800188612 hw 1728907850.800192836, RX hw 1728907850.800195386 sw 1728907850.800211584
(...)
```
If I change it to e.g. 200, it freezes after the "Collecting receiver stats" printf:

```
Using the kernel UTC-TAI offset which is 0
Destination MAC address is 3c:ec:ef:79:27:e9
Link state of node remote is running
Link state of node local is running
         Now:   1728907911.135620629
First wakeup:   1728907911.639999999
   Base time:   1728907911.640000000
  Cycle time:            0.010000000
Collecting receiver stats

```

Then if I run isochron report separately I just get the results from the previous successful run (since I always write to isochron.dat).

I'm not sure if you could have any hint about what could be going on here.

Thanks in advance!

**Comment by vladimiroltean** [comment]
For how long are you waiting until you declare it "frozen"? With a cycle time of 0.01 seconds, sending 200 packets takes 2 seconds, and there is another timeout timer which expires 5 seconds after the receiver has last received anything, so if you wait long enough, just "freeze" isn't the expected behavior. Unless the receiver is stuck for some reason in some other system call.
If you run the receiver under strace, what does it show?

**Comment by JorgeSasiain** [comment]
Hi again, thanks for the response.

Actually the sender takes a bit of time to send all the frames, then shows "Collecting receiver stats" after the expected time for all the frames, and it's then when it lags.

Thanks for the strace tip. I had used it before for attahcing to a running process but this is very useful!

It seems that there is some issue going on once there's IP fragmentation. It fails when the size of the data exceeds it. I will keep looking but I believe isochron isn't at fault, my bad :)
